import { Sometype_Mono } from "next/font/google";
import "./globals.css";
// components
import MainNav from "@/components/MainNav";

const SometypeMono = Sometype_Mono({
  variable: "--font-sometimesMono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${SometypeMono.variable} antialiased overflow-hidden relative`}
      >
        <div className="flex">
          {/* main nav */}
          <div className="hidden 2xl:flex w-[285px] h-screen bg-secondary">
            <MainNav />
          </div>
          <div className="w-full max-w-[1130px] px-[15px] mx-auto">
            <header>header</header>
            <div>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
