// frontend/app/layout.jsx
import "./globals.css";
import { I18nProvider } from "./i18nProvider";
import FontWrapper from "./FontWrapper";

// components
import MainNav from "@/components/MainNav";
import Gradient from "@/components/Gradient";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased relative overflow-x-hidden">
        <div suppressHydrationWarning>
          <I18nProvider>
            <FontWrapper>
              <PageTransition>
                <Gradient />

                <div className="flex min-h-screen">
                  {/* main nav */}
                  <div className="hidden 2xl:flex w-[285px] h-screen bg-secondary">
                    <MainNav />
                  </div>

                  <div className="flex-1 flex flex-col">
                    <div className="w-full max-w-[1130px] px-[15px] mx-auto flex flex-col flex-1">
                      <Header />

                      {/* פה גלילה אנכית בלבד */}
                      <div className="flex-1 overflow-y-auto overflow-x-hidden">
                        {children}
                      </div>
                    </div>

                    <Footer />
                  </div>
                </div>
              </PageTransition>
            </FontWrapper>
          </I18nProvider>
        </div>
      </body>
    </html>
  );
}
